import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import yaml


SCRIPT = Path(__file__).resolve().parents[2] / ".agents/pipeline-core/scripts/featurectl.py"


def run(cmd, cwd, check=True):
    return subprocess.run(cmd, cwd=cwd, check=check, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


class FeatureCtlCoreTests(unittest.TestCase):
    def setUp(self):
        self.tempdir = Path(tempfile.mkdtemp(prefix="featurectl-test-"))
        self.repo = self.make_repo()

    def tearDown(self):
        shutil.rmtree(self.tempdir)

    def make_repo(self):
        repo = self.tempdir / "repo"
        repo.mkdir()
        run(["git", "init", "-b", "main"], repo)
        run(["git", "config", "user.email", "test@example.com"], repo)
        run(["git", "config", "user.name", "Test User"], repo)
        (repo / "README.md").write_text("# Test Repo\n", encoding="utf-8")
        run(["git", "add", "README.md"], repo)
        run(["git", "commit", "-m", "initial"], repo)
        return repo

    def test_init_creates_base_structure_idempotently(self):
        result = run([sys.executable, str(SCRIPT), "init"], self.repo)
        second = run([sys.executable, str(SCRIPT), "init"], self.repo)

        self.assertIn("initialized", result.stdout)
        self.assertIn("initialized", second.stdout)
        self.assertTrue((self.repo / ".ai/features/index.yaml").exists())
        self.assertTrue((self.repo / ".agents/pipeline-core/scripts/schemas").is_dir())
        self.assertTrue((self.repo / ".agents/pipeline-core/references/generated-templates").is_dir())
        self.assertTrue((self.repo / ".agents/skills").is_dir())
        self.assertTrue((self.repo / ".agents/pipeline-core/references").is_dir())
        self.assertTrue((self.repo / "skills/superpowers/subagent-driven-development").is_dir())
        self.assertFalse(list(self.repo.rglob("approvals.yaml")))
        self.assertFalse(list(self.repo.rglob("handoff.md")))

    def test_init_profile_project_updates_source_backed_knowledge(self):
        (self.repo / "package.json").write_text(
            """{
  "name": "profiled-toy-app",
  "scripts": {
    "test": "pytest",
    "build": "echo build"
  }
}
""",
            encoding="utf-8",
        )
        (self.repo / "src/auth").mkdir(parents=True)
        (self.repo / "src/auth/reset_service.py").write_text("def reset_password(): pass\n", encoding="utf-8")
        (self.repo / "src/features/billing/components").mkdir(parents=True)
        (self.repo / "src/features/billing/components/Button.tsx").write_text("export const Button = () => null;\n", encoding="utf-8")
        (self.repo / "tests").mkdir()
        (self.repo / "tests/test_reset_service.py").write_text("def test_reset_password(): pass\n", encoding="utf-8")
        (self.repo / "docs").mkdir()
        (self.repo / "docs/features.md").write_text("# Feature: Reset Password\n", encoding="utf-8")
        (self.repo / "openapi.yaml").write_text("openapi: 3.0.0\n", encoding="utf-8")
        run(["git", "add", "."], self.repo)
        run(["git", "commit", "-m", "add profile sources"], self.repo)

        result = run([sys.executable, str(SCRIPT), "init", "--profile-project"], self.repo)

        self.assertIn("project_profile: updated", result.stdout)
        self.assertIn("project_name: profiled-toy-app", result.stdout)
        self.assertIn("detected_feature_catalog_items:", result.stdout)
        index = yaml.safe_load((self.repo / ".ai/knowledge/project-index.yaml").read_text(encoding="utf-8"))
        self.assertEqual(index["project"]["name"], "profiled-toy-app")
        self.assertGreaterEqual(index["counts"]["source_files"], 1)
        self.assertGreaterEqual(index["counts"]["test_files"], 1)
        self.assertGreaterEqual(len(index["feature_catalog"]), 1)
        self.assertTrue(any(item["name"] == "Reset Password" for item in index["feature_catalog"]))
        self.assertTrue(any(item["name"] == "Billing" for item in index["feature_catalog"]))
        self.assertFalse(any(item["name"] == "Button" for item in index["feature_catalog"]))
        self.assertIn("src/auth/reset_service.py", index["source_examples"])
        self.assertIn("tests/test_reset_service.py", index["test_examples"])
        self.assertIn("openapi.yaml", index["contract_examples"])
        overview = (self.repo / ".ai/knowledge/project-overview.md").read_text(encoding="utf-8")
        self.assertIn("Generated by featurectl project profile", overview)
        self.assertIn("Current Feature Picture", overview)
        self.assertIn("Detected Feature Signals", overview)
        self.assertIn("docs/features.md", overview)
        architecture = (self.repo / ".ai/knowledge/architecture-overview.md").read_text(encoding="utf-8")
        self.assertIn("Feature Topology Reuse", architecture)
        self.assertIn(".ai/knowledge/architecture-overview.md", architecture)
        features = (self.repo / ".ai/knowledge/features-overview.md").read_text(encoding="utf-8")
        self.assertIn("Canonical Feature Memory", features)
        self.assertIn("No canonical features have been promoted yet.", features)
        self.assertNotIn("Reset Password", features)
        discovered = (self.repo / ".ai/knowledge/discovered-signals.md").read_text(encoding="utf-8")
        self.assertIn("Current Feature Picture", discovered)
        self.assertIn("Detected Feature Signals", discovered)
        self.assertIn("Reset Password", discovered)
        self.assertIn("docs/features.md", discovered)

    def test_init_profile_filters_generated_showcase_feature_signals(self):
        (self.repo / "docs").mkdir()
        (self.repo / "docs/features.md").write_text("# Feature: Real Billing Dashboard\n", encoding="utf-8")
        generated = self.repo / "pipeline-lab/showcases/random-feature-stress-runs/20260512/features/01-noisy/artifacts"
        generated.mkdir(parents=True)
        (generated / "feature.md").write_text("# Feature: Generated Stress Artifact\n", encoding="utf-8")
        report = self.repo / "pipeline-lab/showcases/native-emulation-report.md"
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text("# Native Feature Emulation Report\n", encoding="utf-8")
        (self.repo / "features.md").write_text("# Feature: Root Spec Noise\n", encoding="utf-8")
        (self.repo / "plan.md").write_text("# Pipeline Lab Feature Plan\n", encoding="utf-8")
        (self.repo / "vision.md").write_text("# Service Architecture Vision\n", encoding="utf-8")
        run_dir = self.repo / "pipeline-lab/runs/20260512/generated"
        run_dir.mkdir(parents=True)
        (run_dir / "feature.md").write_text("# Feature: Generated Run Artifact\n", encoding="utf-8")
        run(["git", "add", "."], self.repo)
        run(["git", "commit", "-m", "add real and generated feature docs"], self.repo)

        run([sys.executable, str(SCRIPT), "init", "--profile-project"], self.repo)

        index = yaml.safe_load((self.repo / ".ai/knowledge/project-index.yaml").read_text(encoding="utf-8"))
        signals = {item["signal"] for item in index["feature_signals"]}
        sources = {item["source"] for item in index["feature_signals"]}
        catalog_names = {item["name"] for item in index["feature_catalog"]}
        self.assertIn("Feature: Real Billing Dashboard", signals)
        self.assertIn("Real Billing Dashboard", catalog_names)
        self.assertNotIn("Feature: Generated Stress Artifact", signals)
        self.assertNotIn("Generated Stress Artifact", catalog_names)
        self.assertNotIn("Native Feature Emulation Report", signals)
        self.assertNotIn("Feature: Root Spec Noise", signals)
        self.assertNotIn("Pipeline Lab Feature Plan", signals)
        self.assertNotIn("Service Architecture Vision", signals)
        self.assertNotIn("Feature: Generated Run Artifact", signals)
        self.assertFalse(any(source.startswith("pipeline-lab/showcases/") for source in sources))
        self.assertFalse(any(source.startswith("pipeline-lab/runs/") for source in sources))
        discovered = (self.repo / ".ai/knowledge/discovered-signals.md").read_text(encoding="utf-8")
        self.assertIn("Real Billing Dashboard", discovered)
        self.assertNotIn("Generated Stress Artifact", discovered)
        self.assertNotIn("Root Spec Noise", discovered)

    def test_init_outside_git_fails_clearly(self):
        outside = self.tempdir / "outside"
        outside.mkdir()

        result = run([sys.executable, str(SCRIPT), "init"], outside, check=False)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("must be run inside a git repository", result.stderr)

    def test_new_creates_worktree_workspace_and_core_artifacts(self):
        result = self.new_feature("run-20260511-test")

        workspace = self.workspace("run-20260511-test")
        self.assertIn("feature_key: auth/reset-password", result.stdout)
        self.assertTrue((self.tempdir / "worktrees/auth-reset-password-run-20260511-test").is_dir())
        self.assertTrue(workspace.is_dir())
        self.assertTrue((workspace / "apex.md").exists())
        self.assertTrue((workspace / "feature.yaml").exists())
        self.assertTrue((workspace / "state.yaml").exists())
        self.assertTrue((workspace / "execution.md").exists())
        self.assertFalse(list(workspace.rglob("approvals.yaml")))
        self.assertFalse(list(workspace.rglob("handoff.md")))

        feature = yaml.safe_load((workspace / "feature.yaml").read_text(encoding="utf-8"))
        state = yaml.safe_load((workspace / "state.yaml").read_text(encoding="utf-8"))
        self.assertEqual(feature["artifact_contract_version"], "0.1.0")
        self.assertEqual(feature["feature_key"], "auth/reset-password")
        self.assertEqual(feature["domain"], "auth")
        self.assertEqual(feature["slug"], "reset-password")
        self.assertEqual(feature["title"], "Reset Password")
        self.assertEqual(feature["status"], "draft")
        self.assertEqual(feature["branch"], "feature/auth-reset-password-run-20260511-test")
        self.assertEqual(feature["canonical_path"], ".ai/features/auth/reset-password")
        self.assertEqual(feature["workspace_path"], ".ai/feature-workspaces/auth/reset-password--run-20260511-test")
        self.assertEqual(state["current_step"], "context")
        self.assertNotIn("next_skill", state)
        self.assertEqual(state["gates"]["implementation"], "blocked")

        main_branch = run(["git", "rev-parse", "--abbrev-ref", "HEAD"], self.repo)
        feature_branch = run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            self.tempdir / "worktrees/auth-reset-password-run-20260511-test",
        )
        self.assertEqual(main_branch.stdout.strip(), "main")
        self.assertEqual(feature_branch.stdout.strip(), "feature/auth-reset-password-run-20260511-test")

    def test_new_duplicate_run_id_fails_before_workspace_creation(self):
        self.new_feature("run-20260511-dupe")

        result = self.new_feature("run-20260511-dupe", check=False)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("worktree path already exists", result.stderr)

    def test_status_reports_state_and_blockers(self):
        self.new_feature("run-20260511-stat")
        workspace = "../worktrees/auth-reset-password-run-20260511-stat/.ai/feature-workspaces/auth/reset-password--run-20260511-stat"

        result = run([sys.executable, str(SCRIPT), "status", "--workspace", workspace], self.repo)

        self.assertIn("feature_key: auth/reset-password", result.stdout)
        self.assertIn("current_step: context", result.stdout)
        self.assertIn("implementation: blocked", result.stdout)
        self.assertIn("blocking_issues:\n  none", result.stdout)
        self.assertIn("next_step: nfp-01-context", result.stdout)

    def test_status_reports_missing_required_file(self):
        self.new_feature("run-20260511-missing")
        workspace = self.workspace("run-20260511-missing")
        (workspace / "apex.md").unlink()

        result = run([sys.executable, str(SCRIPT), "status", "--workspace", str(workspace)], self.repo)

        self.assertIn("missing apex.md", result.stdout)

    def new_feature(self, run_id, check=True):
        return run(
            [
                sys.executable,
                str(SCRIPT),
                "new",
                "--domain",
                "auth",
                "--title",
                "Reset Password",
                "--run-id",
                run_id,
            ],
            self.repo,
            check=check,
        )

    def workspace(self, run_id):
        return self.tempdir / f"worktrees/auth-reset-password-{run_id}/.ai/feature-workspaces/auth/reset-password--{run_id}"


if __name__ == "__main__":
    unittest.main()
